import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = '/home/ubuntu/simulado-enem-interativo';

/** Questões autorais reformuladas: temas e habilidades inspirados em cadernos oficiais do Inep (2018–2024). */
const questions = [
  [1,'Linguagens, Códigos e suas Tecnologias','Leitura de campanha','Campanhas de cidadania digital','Uma campanha de uma biblioteca traz a frase: “Compartilhe água, não boatos. Confira a fonte antes de repassar.” A escolha do imperativo “Confira” busca','convidar o leitor a abandonar as redes sociais.','orientar uma ação de verificação antes do compartilhamento.','explicar a origem científica de todas as notícias.','substituir a leitura de reportagens por campanhas.','B','O imperativo orienta o leitor a verificar a informação antes de compartilhá-la.'],
  [2,'Linguagens, Códigos e suas Tecnologias','Variação linguística','Oralidade e identidade regional','Em uma entrevista, uma agricultora afirma: “A gente vai chegá cedo na feira, porque o povo gosta de escolhê as frutas.” Nesse contexto, essa fala deve ser compreendida como','prova de incapacidade da entrevistada de se comunicar.','modelo obrigatório para documentos públicos.','marca de variedade linguística associada à situação e ao grupo social.','desvio que impede a compreensão da mensagem.','C','A fala é inteligível e revela uma variedade linguística adequada ao contexto de oralidade.'],
  [3,'Linguagens, Códigos e suas Tecnologias','Ironia','Crônica de costumes','Em uma crônica, lê-se: “A placa dizia ‘fila preferencial’; por isso, todos chegaram antes de quem realmente precisava dela.” O efeito de ironia decorre de','criticar o uso indevido de um direito de prioridade.','elogiar a rapidez das pessoas na fila.','explicar a legislação sobre atendimento.','descrever a organização eficiente do local.','A','A oposição entre o aviso e o comportamento das pessoas cria uma crítica irônica.'],
  [4,'Linguagens, Códigos e suas Tecnologias','Efeito de sentido verbal','Memória e narrativa','No trecho “Quando chovia, o bairro inteiro se reunia na varanda da dona Celina”, o emprego de “chovia” e “se reunia” indica','um acontecimento futuro e incerto.','uma ação única encerrada no passado.','uma ordem dada aos moradores.','um hábito recorrente em um período passado.','D','O pretérito imperfeito indica ações habituais ou durativas no passado.'],
  [5,'Linguagens, Códigos e suas Tecnologias','Arte brasileira','Modernismos e identidades','Um mural urbano combina grafismos indígenas, prédios contemporâneos e personagens de diferentes origens. A obra se aproxima de uma perspectiva que','recusa referências culturais brasileiras.','reelabora elementos da cultura nacional em diálogo com o presente.','defende a separação entre arte popular e arte erudita.','prioriza a cópia fiel de modelos europeus.','B','A combinação de referências locais e contemporâneas valoriza uma identidade cultural plural.'],
  [6,'Linguagens, Códigos e suas Tecnologias','Leitura multissemiótica','Infográficos jornalísticos','Um infográfico sobre descarte de resíduos apresenta ícones de materiais, porcentagens e frases curtas. Sua compreensão depende principalmente de','decorar a ordem dos ícones.','ignorar os números e focar apenas nas cores.','articular informações verbais, numéricas e visuais.','converter todos os dados em um texto literário.','C','O sentido é construído pela integração de diferentes linguagens.'],
  [7,'Linguagens, Códigos e suas Tecnologias','Publicidade','Consumo responsável','Um anúncio de produtos reutilizáveis afirma: “Seu consumo escreve o futuro.” O principal recurso persuasivo é','prometer preço menor que o da concorrência.','atribuir ao consumidor responsabilidade por consequências coletivas.','apresentar dados técnicos sobre produção industrial.','comparar visualmente marcas rivais.','B','A frase associa a escolha de consumo à responsabilidade socioambiental.'],
  [8,'Linguagens, Códigos e suas Tecnologias','Leitura literária','Poesia contemporânea','No poema, o eu lírico afirma: “Meu nome cabe no mar, mas não cabe no rótulo que me deram.” A imagem sugere','recusa a classificações que reduzem a identidade do sujeito.','desejo de abandonar a própria história.','descrição objetiva de um ambiente marítimo.','defesa de regras fixas para a linguagem.','A','A oposição entre mar e rótulo sugere uma identidade ampla, não reduzível a etiquetas.'],
  [9,'Linguagens, Códigos e suas Tecnologias','Cultura digital','Checagem de informações','Uma escola orienta os estudantes a verificar autoria, data e endereço eletrônico antes de divulgar uma notícia. Essa prática contribui para','aumentar o número de mensagens compartilhadas.','eliminar a necessidade de leitura crítica.','transformar opiniões em dados científicos.','avaliar a credibilidade de conteúdos digitais.','D','Os critérios indicados permitem avaliar fontes e reduzir a circulação de desinformação.'],
  [10,'Linguagens, Códigos e suas Tecnologias','Língua inglesa','Leitura de instruções','Em um cartaz em inglês, lê-se: “Wash your hands before meals and after using public transport.” A orientação central do texto é','evitar refeições em espaços públicos.','usar transporte coletivo apenas em dias úteis.','adotar hábitos de higiene em situações cotidianas.','substituir água e sabão por álcool em gel.','C','O texto recomenda higienizar as mãos antes das refeições e após usar transporte coletivo.'],
  [11,'Linguagens, Códigos e suas Tecnologias','Língua espanhola','Serviços públicos','Uma placa informa: “La biblioteca abre de lunes a viernes, de 8 a 18 horas. Préstamos por siete días.” A informação permite concluir que a biblioteca','empresta livros durante uma semana.','funciona somente aos fins de semana.','abre por sete horas diariamente.','realiza empréstimos apenas pela manhã.','A','“Préstamos por siete días” informa o prazo de empréstimo de uma semana.'],
  [12,'Linguagens, Códigos e suas Tecnologias','Corpo e linguagem','Dança e pertencimento','Em uma apresentação, dançarinos formam rodas, alternam passos e convidam o público a acompanhar o ritmo com palmas. A linguagem corporal evidencia','isolamento entre artistas e espectadores.','construção coletiva de participação e pertencimento.','substituição da música por fala formal.','rejeição de tradições populares.','B','A roda e o convite às palmas produzem participação compartilhada.'],
  [13,'Linguagens, Códigos e suas Tecnologias','Teatro','Elementos cênicos','Em uma peça, a iluminação muda de tons claros para sombras azuladas quando a personagem passa a recordar uma perda. Nesse caso, a iluminação contribui para','informar o horário real da encenação.','substituir totalmente a atuação dos intérpretes.','esconder a mudança de cena do público.','criar uma atmosfera emocional ligada à memória.','D','A mudança de luz ajuda a construir o clima emocional da cena.'],
  [14,'Linguagens, Códigos e suas Tecnologias','Música e cultura','Matrizes culturais brasileiras','Uma canção atual mistura batida eletrônica, instrumento de tradição regional e versos sobre a vida no interior. Essa composição demonstra','apagamento de referências culturais locais.','recriação de tradições em diálogo com novas linguagens.','uso obrigatório de apenas um gênero musical.','separação entre cultura urbana e cultura regional.','B','A canção atualiza referências regionais ao combiná-las com recursos contemporâneos.'],
  [15,'Linguagens, Códigos e suas Tecnologias','Gênero autobiográfico','Narrativas de si','Em um texto, a narradora registra: “Guardei o bilhete do primeiro ônibus que peguei sozinha; ele me lembrava que eu podia escolher caminhos.” A marca autobiográfica está na','relato de experiência pessoal em primeira pessoa.','apresentação de dados estatísticos sobre mobilidade.','explicação impessoal de uma rota urbana.','presença de instruções para o leitor.','A','O texto relata uma memória individual narrada em primeira pessoa.'],
  [16,'Linguagens, Códigos e suas Tecnologias','Patrimônio cultural','Saberes tradicionais','A renda de bilro, produzida por artesãs de uma comunidade litorânea, é ensinada entre gerações e identifica o grupo. Ela pode ser reconhecida como patrimônio','genético, por estar ligada a famílias específicas.','natural, por depender da paisagem local.','imaterial, por envolver conhecimento e prática cultural.','arquitetônico, por ocupar um espaço físico.','C','Trata-se de um saber-fazer transmitido e compartilhado socialmente, portanto imaterial.'],
  [17,'Linguagens, Códigos e suas Tecnologias','Resenha','Argumentação crítica','Uma resenha afirma: “O filme evita explicar tudo e confia no espectador; por isso, transforma o silêncio em parte da narrativa.” O trecho apresenta','um resumo cronológico de todas as cenas.','uma avaliação argumentada sobre uma escolha estética.','uma instrução técnica para filmagem.','uma informação sobre bilheteria.','B','O autor avalia e justifica o efeito de uma escolha narrativa do filme.'],
  [18,'Linguagens, Códigos e suas Tecnologias','Meme','Relação verbal e visual','Um meme mostra uma pessoa com muitas abas abertas no computador e a legenda “Eu: vou dormir cedo. Também eu às 2h: só mais uma pesquisa.” O humor resulta da','ausência de relação entre imagem e legenda.','explicação científica sobre o sono.','defesa do uso ilimitado de telas.','contraste entre a intenção declarada e a ação mostrada.','D','A legenda e a imagem contrapõem a intenção de dormir cedo ao comportamento de continuar online.'],
  [19,'Linguagens, Códigos e suas Tecnologias','Divulgação científica','Uso de fontes','Uma reportagem científica inclui a fala de uma pesquisadora e o resultado de um estudo. A citação dessas fontes tem a função de','substituir a interpretação do leitor.','tornar o texto exclusivamente opinativo.','sustentar a informação com vozes e evidências especializadas.','eliminar qualquer necessidade de contexto.','C','As fontes qualificam e sustentam a informação divulgada.'],
  [20,'Linguagens, Códigos e suas Tecnologias','Norma-padrão','Concordância verbal','Para uma ata de reunião, a redação adequada é','Houve problemas na entrega dos materiais.','Houveram problemas na entrega dos materiais.','Faziam dois meses que a entrega atrasou.','Existiu atrasos na entrega dos materiais.','A','O verbo haver, no sentido de existir, é impessoal e fica no singular.'],
  [21,'Linguagens, Códigos e suas Tecnologias','Foco narrativo','Narrador e incerteza','No conto, o narrador afirma: “Talvez ela tivesse voltado. Talvez eu apenas quisesse que isso fosse verdade.” Essas marcas indicam','certeza documental sobre os fatos.','uma perspectiva subjetiva e duvidosa do narrador.','descrição objetiva de uma pesquisa histórica.','ordem dirigida a outra personagem.','B','“Talvez” evidencia incerteza e subjetividade da voz narrativa.'],
  [22,'Linguagens, Códigos e suas Tecnologias','Texto instrucional','Linguagem pública','Um manual de defesa civil orienta: “Em caso de alagamento, desligue a energia e procure um local elevado.” Predomina nesse trecho a função de','entreter com uma situação ficcional.','narrar uma experiência passada.','expressar sentimentos do autor.','orientar procedimentos diante de um risco.','D','O texto dá instruções objetivas para agir em situação de emergência.'],
  [23,'Linguagens, Códigos e suas Tecnologias','Registro informal','Adequação comunicativa','Em uma conversa entre colegas, a expressão “a gente dá um jeito” significa, no contexto,','seguir uma norma jurídica específica.','abandonar uma tarefa sem solução.','encontrar uma solução prática, mesmo sem detalhá-la.','registrar formalmente uma decisão.','C','A expressão informal indica a intenção de resolver uma situação de modo prático.'],
  [24,'Linguagens, Códigos e suas Tecnologias','E-mail formal','Planejamento textual','Para solicitar uma visita técnica a um museu, o assunto de e-mail mais adequado é','Oi, tudo bem?','Solicitação de visita técnica — Escola [nome] — 12 de setembro','Preciso falar com vocês urgente','Museu legal para a turma','B','O assunto é claro, identificável e informa a finalidade e a data da solicitação.'],
  [25,'Linguagens, Códigos e suas Tecnologias','Coesão referencial','Leitura de projeto','Leia: “O bairro criou uma horta comunitária. Essa iniciativa reúne moradores, reduz resíduos orgânicos e amplia o acesso a alimentos.” A expressão “Essa iniciativa” retoma','a criação da horta comunitária.','somente os resíduos orgânicos.','a palavra “moradores”.','a falta de alimentos no bairro.','A','O demonstrativo retoma a ação apresentada na frase anterior: criar a horta.'],

  [26,'Ciências Humanas e suas Tecnologias','Colonização','Administração colonial','As capitanias hereditárias foram criadas pela Coroa portuguesa no século XVI. Entre seus objetivos estava','garantir independência política imediata às colônias.','abolir a exploração de recursos naturais.','substituir o comércio marítimo por feiras locais.','ocupar e administrar territórios com participação de particulares.','D','As capitanias buscavam ocupar e administrar o território mediante concessões a donatários.'],
  [27,'Ciências Humanas e suas Tecnologias','Povos indígenas','Resistências à colonização','Ao estudar a presença indígena na formação do Brasil, uma turma identifica estratégias como deslocamentos, alianças e manutenção de práticas culturais. Essas estratégias revelam','passividade total diante da colonização.','formas diversas de resistência e negociação.','abandono completo de territórios ancestrais.','aceitação uniforme da catequização.','B','Os povos indígenas atuaram de formas variadas, resistindo e negociando em diferentes contextos.'],
  [28,'Ciências Humanas e suas Tecnologias','Abolição e pós-abolição','Desigualdade social','A Lei Áurea extinguiu juridicamente a escravidão em 1888, mas não assegurou terra, moradia ou inserção econômica à população liberta. Uma consequência histórica dessa ausência foi','manutenção de desigualdades raciais e socioeconômicas.','distribuição imediata de propriedades rurais.','universalização do voto feminino.','fim de todas as formas de discriminação.','A','A ausência de políticas de integração contribuiu para a persistência de desigualdades.'],
  [29,'Ciências Humanas e suas Tecnologias','Era Vargas','Estado e trabalho','A criação de leis trabalhistas e o fortalecimento de órgãos estatais, especialmente a partir de 1930, indicam','descentralização completa do poder político.','retorno ao pacto colonial.','ampliação da intervenção do Estado nas relações de trabalho.','eliminação de conflitos entre trabalhadores e empresários.','C','O período marcou maior atuação estatal na regulamentação do trabalho.'],
  [30,'Ciências Humanas e suas Tecnologias','Redemocratização','Movimentos sociais','No final da década de 1970, greves e mobilizações por anistia e eleições diretas ganharam visibilidade. Esses movimentos contribuíram para','restaurar o regime colonial.','impedir a organização da sociedade civil.','substituir a Constituição por decretos militares.','pressionar pela abertura política e por direitos democráticos.','D','As mobilizações fortaleceram a luta pela redemocratização.'],
  [31,'Ciências Humanas e suas Tecnologias','Amazônia','Atividades econômicas e ambiente','Em uma região de floresta, a abertura de estradas facilita o escoamento de produtos, mas também pode estimular ocupação desordenada e retirada de vegetação. Esse processo evidencia','separação completa entre economia e ambiente.','redução automática da pressão sobre os recursos.','conflitos entre expansão econômica, território e conservação.','desaparecimento das populações locais em todos os casos.','C','A infraestrutura pode favorecer atividades econômicas e aumentar pressões socioambientais.'],
  [32,'Ciências Humanas e suas Tecnologias','Climatologia urbana','Ilhas de calor','Em áreas densamente construídas, a substituição de árvores por asfalto e concreto contribui para temperaturas mais elevadas. Esse fenômeno é intensificado pela','maior reflexão da radiação em áreas vegetadas.','impermeabilização do solo e redução da cobertura vegetal.','diminuição do consumo de energia.','presença exclusiva de rios urbanos.','B','Pavimentação e pouca vegetação favorecem o armazenamento de calor.'],
  [33,'Ciências Humanas e suas Tecnologias','Cartografia','Coordenadas geográficas','Uma cidade localizada a 10° S e 45° W encontra-se, respectivamente, nos hemisférios','Norte e Oriental.','Norte e Ocidental.','Sul e Oriental.','Sul e Ocidental.','D','Latitude sul indica Hemisfério Sul; longitude oeste indica Hemisfério Ocidental.'],
  [34,'Ciências Humanas e suas Tecnologias','Urbanização','Mobilidade','Uma prefeitura integra linhas de ônibus, ciclovias e trem metropolitano com uma única tarifa. A medida procura principalmente','reduzir a dependência de deslocamentos individuais motorizados.','impedir o acesso de moradores da periferia ao centro.','substituir todo deslocamento a pé.','aumentar o número de estacionamentos centrais.','A','A integração estimula transporte coletivo e alternativas ao automóvel individual.'],
  [35,'Ciências Humanas e suas Tecnologias','Espaço agrário','Tecnificação agrícola','A adoção de máquinas, sementes selecionadas e sistemas de irrigação pode elevar a produtividade agrícola. Ao mesmo tempo, esse processo pode','eliminar toda diferença entre pequenas e grandes propriedades.','aprofundar desigualdades quando o acesso à tecnologia é concentrado.','impedir a comercialização de commodities.','tornar desnecessário o trabalho qualificado.','B','A tecnologia pode ampliar produtividade, mas seu acesso desigual tende a aprofundar assimetrias.'],
  [36,'Ciências Humanas e suas Tecnologias','Demografia','Transição demográfica','Uma pirâmide etária apresenta base mais estreita que a observada décadas antes e maior participação de adultos e idosos. Esse perfil sugere','aumento imediato da taxa de natalidade.','retorno a uma população exclusivamente rural.','redução da fecundidade e envelhecimento populacional.','desaparecimento de migrações internas.','C','Base estreita e topo relativamente maior indicam menos nascimentos e envelhecimento.'],
  [37,'Ciências Humanas e suas Tecnologias','Cartografia temática','Leitura de mapas','Para comparar a incidência de uma doença entre municípios com populações muito diferentes, o indicador mais adequado no mapa é','o número absoluto de casos, sem relação com a população.','a taxa de casos por número de habitantes.','a cor favorita dos moradores.','a ordem alfabética dos municípios.','B','Taxas permitem comparar a ocorrência proporcional entre populações de tamanhos distintos.'],
  [38,'Ciências Humanas e suas Tecnologias','Globalização','Redes produtivas','Um celular é projetado em um país, montado em outro e utiliza componentes fabricados em diferentes continentes. Essa organização expressa','isolamento das economias nacionais.','fim das trocas internacionais.','produção artesanal local como regra global.','fragmentação internacional das etapas produtivas.','D','A produção é distribuída entre lugares conectados por cadeias globais.'],
  [39,'Ciências Humanas e suas Tecnologias','Recursos hídricos','Bacias hidrográficas','O desmatamento em nascentes pode aumentar a erosão e o transporte de sedimentos para rios situados a jusante. Isso ocorre porque','as águas conectam partes de uma mesma bacia hidrográfica.','cada nascente funciona sem relação com os rios.','sedimentos não são transportados pela água.','a vegetação não interfere no solo.','A','Os cursos d’água conectam áreas a montante e a jusante da bacia.'],
  [40,'Ciências Humanas e suas Tecnologias','Filosofia antiga','Diálogo socrático','Ao responder a uma pergunta com novas perguntas, Sócrates buscava levar o interlocutor a examinar suas próprias ideias. Essa prática valoriza','a repetição de respostas prontas.','a investigação crítica por meio do diálogo.','a recusa de qualquer argumento.','a imposição de uma verdade sem debate.','B','O diálogo socrático estimula exame crítico e construção argumentativa.'],
  [41,'Ciências Humanas e suas Tecnologias','Iluminismo','Direitos e cidadania','A defesa de que governos devem ser legitimados pelo consentimento dos governados aproxima-se de ideias iluministas porque afirma','origem divina e incontestável de todo poder.','retorno aos privilégios de nascimento.','direitos políticos e limitação do poder arbitrário.','submissão permanente dos cidadãos ao monarca.','C','O Iluminismo valorizou direitos, consentimento e limitação do poder.'],
  [42,'Ciências Humanas e suas Tecnologias','Sociologia','Fato social','Regras de trânsito existem antes de cada motorista, exercem pressão sobre sua conduta e são compartilhadas socialmente. Para Durkheim, esse exemplo caracteriza','uma escolha puramente individual.','um instinto biológico imutável.','uma opinião sem efeito coletivo.','um fato social exterior e coercitivo.','D','As regras sociais são exteriores ao indivíduo e orientam sua ação coletivamente.'],
  [43,'Ciências Humanas e suas Tecnologias','Sociologia do trabalho','Alienação','Quando trabalhadores não controlam o processo nem o destino do produto de seu trabalho, a situação exemplifica, em Marx,','alienação do trabalho.','democracia direta.','mobilidade social automática.','neutralidade das relações de produção.','A','A separação entre trabalhador, processo e produto é central na noção de alienação.'],
  [44,'Ciências Humanas e suas Tecnologias','Cidadania','Participação social','Um conselho municipal reúne moradores, gestores e entidades para discutir prioridades de saúde. Essa experiência fortalece','a concentração exclusiva de decisões em uma pessoa.','a gestão participativa de políticas públicas.','a substituição de eleições por sorteio.','a proibição de controle social.','B','Conselhos ampliam participação e controle social sobre políticas públicas.'],
  [45,'Ciências Humanas e suas Tecnologias','Antropologia','Relativismo cultural','Ao analisar uma prática cultural diferente da sua, uma estudante procura compreendê-la no contexto dos valores do próprio grupo, sem classificá-la como superior ou inferior. Essa atitude expressa','etnocentrismo.','determinismo biológico.','relativismo cultural.','racismo científico.','C','O relativismo cultural busca compreender práticas a partir de seus contextos.'],
  [46,'Ciências Humanas e suas Tecnologias','História das mulheres','Direitos políticos','As lutas pelo voto feminino no Brasil contribuíram para','ampliar a participação política das mulheres.','restaurar o voto censitário.','impedir candidaturas femininas.','reduzir direitos civis.','A','O sufrágio feminino ampliou direitos de participação política.'],
  [47,'Ciências Humanas e suas Tecnologias','Desigualdade social','Acesso a serviços','Durante uma crise sanitária, bairros com menos saneamento, moradias mais adensadas e menor acesso a serviços de saúde enfrentam riscos maiores. A situação evidencia','igualdade automática de exposição aos riscos.','ausência de relação entre território e saúde.','exclusividade de causas individuais.','como desigualdades sociais produzem vulnerabilidades diferenciadas.','D','As condições de moradia e acesso a serviços tornam grupos mais vulneráveis.'],
  [48,'Ciências Humanas e suas Tecnologias','Memória e direitos humanos','Patrimônio histórico','A transformação de um antigo local de repressão em espaço de memória e educação tem como finalidade','apagar conflitos do passado.','preservar lembranças e prevenir a repetição de violações.','substituir documentos históricos por ficção.','impedir debates sobre cidadania.','B','Lugares de memória favorecem reflexão sobre violações e direitos.'],
  [49,'Ciências Humanas e suas Tecnologias','Tecnologia e sociedade','Algoritmos e informação','Quando uma plataforma recomenda repetidamente conteúdos semelhantes aos que o usuário já consumiu, ela pode','eliminar toda seleção de informações.','garantir contato com todas as perspectivas.','reforçar bolhas informacionais e polarização.','substituir o debate público por dados neutros.','C','Recomendações personalizadas podem restringir a diversidade de pontos de vista.'],
  [50,'Ciências Humanas e suas Tecnologias','Direitos territoriais','Povos indígenas','A demarcação de terras indígenas é defendida como instrumento de proteção de modos de vida, línguas e vínculos territoriais. Essa defesa se relaciona ao reconhecimento de','direitos coletivos e diversidade cultural.','privilégios individuais sem relação territorial.','eliminação da cidadania indígena.','uso obrigatório de um único idioma.','A','A demarcação protege direitos coletivos e a continuidade cultural de povos indígenas.'],

  [51,'Ciências da Natureza e suas Tecnologias','Ecologia e clima','Efeito estufa','O aumento da concentração de dióxido de carbono na atmosfera intensifica o efeito estufa porque esse gás','reflete toda a luz solar para o espaço.','absorve parte da radiação infravermelha emitida pela superfície.','impede a entrada de oxigênio na atmosfera.','transforma diretamente nitrogênio em calor.','B','O CO₂ absorve radiação infravermelha, contribuindo para a retenção de energia térmica.'],
  [52,'Ciências da Natureza e suas Tecnologias','Ecologia','Bioacumulação','Em uma cadeia alimentar aquática, um pesticida persistente é ingerido por organismos menores e se concentra ao longo dos níveis tróficos. A maior concentração tende a ocorrer','nas algas produtoras, exclusivamente.','na água, antes de qualquer organismo.','em todos os níveis na mesma proporção.','nos predadores do topo da cadeia.','D','Substâncias persistentes podem se biomagnificar até os níveis tróficos superiores.'],
  [53,'Ciências da Natureza e suas Tecnologias','Imunologia','Vacinação','Em uma comunidade com alta cobertura vacinal, até pessoas não vacinadas podem ter menor chance de contato com o agente infeccioso. Isso ocorre porque a vacinação','reduz a circulação do agente entre pessoas suscetíveis.','substitui permanentemente todos os tratamentos.','aumenta a mutação dos vírus.','elimina a necessidade de higiene.','A','A vacinação reduz pessoas suscetíveis e dificulta a transmissão na comunidade.'],
  [54,'Ciências da Natureza e suas Tecnologias','Biologia celular','Fotossíntese','Em um experimento, plantas recebem quantidades crescentes de luz, enquanto temperatura e concentração de CO₂ permanecem constantes. Inicialmente, a taxa de fotossíntese aumenta e depois se estabiliza. A estabilização indica que','a luz deixou de existir.','a planta passou a respirar apenas.','outro fator passou a limitar a taxa do processo.','a clorofila foi transformada em CO₂.','C','Com luz suficiente, outro fator, como CO₂ ou enzimas, passa a limitar a fotossíntese.'],
  [55,'Ciências da Natureza e suas Tecnologias','Genética','Herança recessiva','Um casal sem manifestação de uma doença genética recessiva tem um filho afetado. Considerando apenas esse gene, a explicação mais provável é que','ambos os pais sejam homozigotos dominantes.','ambos os pais sejam heterozigotos portadores.','a doença seja necessariamente dominante.','o filho não tenha recebido genes dos pais.','B','Pais heterozigotos podem transmitir os dois alelos recessivos a um filho.'],
  [56,'Ciências da Natureza e suas Tecnologias','Fisiologia humana','Regulação da água corporal','Após várias horas sem ingerir água, o organismo tende a liberar mais hormônio antidiurético (ADH). Esse aumento favorece','maior perda de água pela urina.','produção de glicose pelos rins.','redução da reabsorção de água.','maior reabsorção de água nos rins.','D','O ADH aumenta a reabsorção de água, ajudando a conservar líquidos.'],
  [57,'Ciências da Natureza e suas Tecnologias','Bioquímica','Enzimas','Uma enzima perde a atividade quando submetida a temperatura muito elevada. Isso pode ocorrer porque o aquecimento','altera a estrutura tridimensional do sítio ativo.','transforma a enzima em DNA.','aumenta indefinidamente a velocidade da reação.','elimina a necessidade de substrato.','A','Temperaturas extremas podem desnaturar a enzima e modificar seu sítio ativo.'],
  [58,'Ciências da Natureza e suas Tecnologias','Eletroquímica','Oxidação','Em uma pilha, uma lâmina de zinco perde massa enquanto fornece elétrons ao circuito. Nessa lâmina ocorre','redução de íons metálicos.','neutralização ácido-base.','oxidação do zinco.','condensação de vapor.','C','Perder elétrons caracteriza oxidação; por isso o zinco metálico se consome.'],
  [59,'Ciências da Natureza e suas Tecnologias','Química','Separação de misturas','Para obter água potável a partir de água salgada em um sistema simples, uma técnica adequada é','filtração em papel.','destilação, com evaporação e condensação da água.','decantação do sal sólido.','peneiração da solução.','B','Na destilação, a água evapora e condensa, separando-se dos sais dissolvidos.'],
  [60,'Ciências da Natureza e suas Tecnologias','Química ambiental','Correção de acidez','Um solo muito ácido pode receber calcário, rico em carbonato de cálcio, para elevar seu pH. Essa prática se explica porque o carbonato atua como','substância básica que neutraliza parte da acidez.','ácido forte que aumenta a concentração de H⁺.','sal inerte sem interação com o solo.','catalisador que produz água sem reagir.','A','O carbonato tem comportamento básico e reduz a acidez do solo.'],
  [61,'Ciências da Natureza e suas Tecnologias','Química orgânica','Combustão','Na combustão completa do etanol, em presença suficiente de oxigênio, os principais produtos são','monóxido de carbono e hidrogênio.','metano e oxigênio.','apenas água líquida.','dióxido de carbono e água.','D','A combustão completa de compostos orgânicos produz CO₂ e H₂O.'],
  [62,'Ciências da Natureza e suas Tecnologias','Materiais','Polímeros','Alguns plásticos podem ser aquecidos, moldados e resfriados repetidas vezes sem alteração química predominante. Esses materiais são classificados como','termoendurecíveis.','termoplásticos.','metais puros.','cerâmicas refratárias.','B','Termoplásticos amolecem com aquecimento e podem ser remodelados.'],
  [63,'Ciências da Natureza e suas Tecnologias','Eletroquímica','Pilhas e corrosão','A ferrugem do ferro é um processo de corrosão em que o metal participa de reações envolvendo perda de elétrons. Logo, o ferro sofre','oxidação.','fusão.','sublimação.','neutralização.','A','A corrosão do ferro envolve sua oxidação, isto é, perda de elétrons.'],
  [64,'Ciências da Natureza e suas Tecnologias','Física moderna','Radioatividade','Em serviços de saúde, materiais radioativos devem ser armazenados em recipientes adequados e manipulados com tempo de exposição reduzido. Essas medidas buscam','aumentar a emissão de radiação.','reduzir a dose de radiação recebida pelas pessoas.','transformar radiação em som.','eliminar a massa dos átomos.','B','Blindagem, distância e menor tempo de exposição reduzem a dose recebida.'],
  [65,'Ciências da Natureza e suas Tecnologias','Eletricidade','Consumo de energia','Um chuveiro de 5,5 kW é usado 20 minutos por dia durante 30 dias. O consumo aproximado de energia, em kWh, é','5,5 kWh.','18,3 kWh.','55 kWh.','165 kWh.','C','5,5 × (20/60) × 30 = 55 kWh.'],
  [66,'Ciências da Natureza e suas Tecnologias','Termologia','Condução térmica','Ao segurar uma colher metálica deixada em uma panela quente, a mão pode sentir calor mesmo sem tocar a chama. O fenômeno principal é','condução de energia térmica pelo metal.','refração da luz no ar.','produção de energia elétrica pela colher.','evaporação do metal.','A','Metais conduzem energia térmica por suas partículas e elétrons livres.'],
  [67,'Ciências da Natureza e suas Tecnologias','Óptica','Lentes corretivas','Uma pessoa míope enxerga objetos próximos com nitidez, mas tem dificuldade para ver objetos distantes. A correção usual utiliza lente','convergente, para aumentar a convergência dos raios.','plana, para não alterar os raios.','cilíndrica, para medir massa.','divergente, para afastar o foco antes de ele atingir a retina.','D','Na miopia, lentes divergentes deslocam o foco para a retina.'],
  [68,'Ciências da Natureza e suas Tecnologias','Cinemática','Velocidade média','Um veículo percorre 180 km em 3 h, mantendo velocidade média constante. Sua velocidade média é','30 km/h.','60 km/h.','90 km/h.','540 km/h.','B','Velocidade média = distância/tempo = 180/3 = 60 km/h.'],
  [69,'Ciências da Natureza e suas Tecnologias','Eletricidade','Lei de Ohm','Um resistor de 6 Ω é ligado a uma fonte de 12 V. A corrente elétrica no resistor vale','2 A.','6 A.','12 A.','72 A.','A','Pela lei de Ohm, I = V/R = 12/6 = 2 A.'],
  [70,'Ciências da Natureza e suas Tecnologias','Energia','Efeito fotovoltaico','Em painéis solares fotovoltaicos, a energia da luz é convertida predominantemente em energia','química armazenada em combustíveis.','nuclear liberada por átomos.','elétrica disponível no circuito.','mecânica do vento.','C','O efeito fotovoltaico transforma energia luminosa em energia elétrica.'],
  [71,'Ciências da Natureza e suas Tecnologias','Ondulatória','Som','Dois sons emitidos por instrumentos diferentes têm a mesma intensidade, mas um é mais agudo que o outro. O som mais agudo possui maior','frequência.','amplitude obrigatoriamente.','velocidade no ar.','comprimento do instrumento, necessariamente.','A','A altura (grave/agudo) do som está associada à frequência.'],
  [72,'Ciências da Natureza e suas Tecnologias','Hidrostática','Pressão em líquidos','Em água de densidade 1000 kg/m³, adotando g = 10 m/s², a pressão adicional a 2 m de profundidade é','2 000 Pa.','20 000 Pa.','50 000 Pa.','200 000 Pa.','B','p = ρgh = 1000 × 10 × 2 = 20 000 Pa.'],
  [73,'Ciências da Natureza e suas Tecnologias','Propriedades da matéria','Densidade','Um objeto de massa 200 g ocupa volume de 250 mL. Como sua densidade é 0,8 g/mL, ele tende a, quando colocado em água de densidade 1,0 g/mL,','afundar rapidamente.','permanecer em qualquer profundidade.','dissolver completamente.','flutuar.','D','Como a densidade do objeto é menor que a da água, ele flutua.'],
  [74,'Ciências da Natureza e suas Tecnologias','Termologia','Dilatação térmica','Juntas de dilatação em pontes e trilhos são instaladas para','permitir variações de comprimento causadas pela temperatura.','impedir toda troca de calor com o ambiente.','aumentar a massa das estruturas.','reduzir a gravidade local.','A','As juntas acomodam dilatação e contração térmicas.'],
  [75,'Ciências da Natureza e suas Tecnologias','Química ambiental','Eutrofização','O lançamento excessivo de esgoto rico em nutrientes em lagoas pode favorecer crescimento intenso de algas e reduzir o oxigênio disponível. Esse processo é chamado de','filtração.','eutrofização.','sublimação.','destilação.','B','O excesso de nutrientes provoca proliferação de algas e alterações no oxigênio do ambiente aquático.'],

  [76,'Matemática e suas Tecnologias','Porcentagem','Descontos sucessivos','Uma escola adquiriu 240 vouchers de um curso. Em uma campanha, 15% deles serão vendidos com desconto de R$ 30,00 cada. O valor total dos descontos será','R$ 720,00.','R$ 1.080,00.','R$ 2.400,00.','R$ 7.200,00.','B','15% de 240 é 36; 36 × 30 = 1.080.'],
  [77,'Matemática e suas Tecnologias','Média ponderada','Avaliação escolar','Uma estudante obteve nota 6 em uma atividade com peso 2 e nota 8 em uma prova com peso 3. Sua média ponderada é','6,8.','7,0.','7,2.','7,5.','C','(6×2 + 8×3)/(2+3) = 36/5 = 7,2.'],
  [78,'Matemática e suas Tecnologias','Grandezas proporcionais','Vazão','Uma torneira libera 18 litros de água por minuto. Mantida aberta por 15 minutos, ela libera','270 litros.','120 litros.','33 litros.','3 litros.','A','18 × 15 = 270 litros.'],
  [79,'Matemática e suas Tecnologias','Função afim','Modelagem','O custo de uma corrida é dado por C(x) = 2x + 5, em que x é a distância em quilômetros e C é o valor em reais. Para 7 km, o custo será','R$ 12,00.','R$ 14,00.','R$ 17,00.','R$ 19,00.','D','C(7) = 2×7 + 5 = 19.'],
  [80,'Matemática e suas Tecnologias','Porcentagem','Desconto simples','Um livro custa R$ 150,00 e entra em promoção com 20% de desconto. O novo preço é','R$ 100,00.','R$ 120,00.','R$ 130,00.','R$ 170,00.','B','20% de 150 é 30; 150 − 30 = 120.'],
  [81,'Matemática e suas Tecnologias','Estatística','Mediana','As idades de cinco voluntários são 12, 15, 15, 17 e 21 anos. A mediana dessas idades é','12.','14.','15.','16.','C','Com os dados ordenados, o valor central é 15.'],
  [82,'Matemática e suas Tecnologias','Probabilidade','Eventos simples','Uma caixa contém 3 bolas vermelhas, 2 azuis e 5 verdes. Ao retirar uma bola ao acaso, a probabilidade de ela ser vermelha é','3/10.','1/2.','2/5.','5/10.','A','Há 3 bolas vermelhas entre 10 bolas no total.'],
  [83,'Matemática e suas Tecnologias','Geometria espacial','Volume de cilindro','Um reservatório cilíndrico tem raio interno de 3 m e altura de 10 m. Usando V = πr²h, seu volume é','30π m³.','60π m³.','80π m³.','90π m³.','D','V = π × 3² × 10 = 90π m³.'],
  [84,'Matemática e suas Tecnologias','Escala','Mapas','Em um mapa na escala 1:5 000, uma rua mede 3 cm. O comprimento real aproximado da rua é','15 m.','50 m.','150 m.','1 500 m.','C','3 cm no mapa correspondem a 15 000 cm = 150 m no real.'],
  [85,'Matemática e suas Tecnologias','Geometria plana','Área de triângulo','Um canteiro triangular tem base de 18 m e altura de 12 m. Sua área é','54 m².','108 m².','180 m².','216 m².','B','A = (18×12)/2 = 108 m².'],
  [86,'Matemática e suas Tecnologias','Álgebra','Equação do 1.º grau','A solução da equação 3x + 2 = 20 é','6.','8.','18.','22.','A','3x = 18, portanto x = 6.'],
  [87,'Matemática e suas Tecnologias','Função exponencial','Crescimento percentual','Uma aplicação de R$ 800,00 rende 10% ao mês, com juros compostos, durante dois meses. O montante será','R$ 880,00.','R$ 900,00.','R$ 960,00.','R$ 968,00.','D','800 × 1,1² = 800 × 1,21 = 968.'],
  [88,'Matemática e suas Tecnologias','Análise combinatória','Formação de duplas','Cinco estudantes se inscreveram para formar uma dupla de apresentação. O número de duplas distintas possíveis é','5.','8.','10.','20.','C','O número de combinações de 5 elementos tomados 2 a 2 é 5×4/2 = 10.'],
  [89,'Matemática e suas Tecnologias','Função afim','Variação de temperatura','A temperatura de uma sala era 28 °C e diminuiu 2 °C por hora. Após 6 horas, a temperatura será','10 °C.','16 °C.','20 °C.','26 °C.','B','28 − 2×6 = 16 °C.'],
  [90,'Matemática e suas Tecnologias','Razão e proporção','Divisão proporcional','Uma faixa de 50 m será dividida em partes branca e azul na razão 4:6. O comprimento da parte branca será','15 m.','20 m.','25 m.','30 m.','B','A parte branca é 4/(4+6) de 50, isto é, 20 m.'],
  [91,'Matemática e suas Tecnologias','Matemática financeira','Consumo de combustível','Um carro percorre 12 km por litro. Em uma viagem de 330 km, com gasolina a R$ 5,80 por litro, o gasto aproximado com combustível será','R$ 137,50.','R$ 159,50.','R$ 191,40.','R$ 275,00.','B','São necessários 330/12 = 27,5 L; 27,5 × 5,80 = 159,50.'],
  [92,'Matemática e suas Tecnologias','Estatística','Média aritmética','As vendas diárias de uma pequena feira foram 20, 25, 25 e 30 unidades em quatro dias. A média de unidades vendidas por dia foi','20.','22,5.','24.','25.','D','(20+25+25+30)/4 = 100/4 = 25.'],
  [93,'Matemática e suas Tecnologias','Geometria plana','Área de quadrado','Uma placa quadrada possui área de 1,44 m². A medida de seu lado é','0,72 m.','1,20 m.','1,44 m.','2,88 m.','B','O lado é a raiz quadrada de 1,44: 1,2 m.'],
  [94,'Matemática e suas Tecnologias','Geometria espacial','Volume de paralelepípedo','Uma caixa retangular mede 2 m de comprimento, 3 m de largura e 5 m de altura. Seu volume é','10 m³.','15 m³.','30 m³.','60 m³.','C','V = 2 × 3 × 5 = 30 m³.'],
  [95,'Matemática e suas Tecnologias','Medidas','Conversão de capacidade','Uma jarra contém 2,4 L de suco e serve igualmente 12 copos. Cada copo recebe','200 mL.','240 mL.','288 mL.','2 000 mL.','A','2,4 L = 2 400 mL; 2 400/12 = 200 mL.'],
  [96,'Matemática e suas Tecnologias','Porcentagem','Variações sucessivas','Um produto sofre aumento de 10% e, no mês seguinte, desconto de 10% sobre o novo preço. Comparado ao preço inicial, o preço final fica','10% maior.','igual ao inicial.','10% menor.','1% menor.','D','Multiplica-se por 1,10 e depois por 0,90: 0,99 do preço inicial, ou 1% menor.'],
  [97,'Matemática e suas Tecnologias','Sequências','Progressão aritmética','Em quatro filas de cadeiras, há respectivamente 12, 14, 16 e 18 lugares. O total de lugares é','48.','60.','64.','72.','B','12 + 14 + 16 + 18 = 60.'],
  [98,'Matemática e suas Tecnologias','Porcentagem','Leitura de dados','Em uma turma, 30% dos estudantes estavam ausentes, o que corresponde a 12 estudantes. O total de estudantes da turma é','30.','36.','40.','48.','C','Se 30% = 12, então 100% = 12/0,30 = 40.'],
  [99,'Matemática e suas Tecnologias','Unidades de medida','Conversão de comprimento','Uma fita de 0,25 m equivale a','25 cm.','2,5 cm.','250 cm.','2 500 cm.','A','1 m = 100 cm; 0,25 m = 25 cm.'],
  [100,'Matemática e suas Tecnologias','Probabilidade','Lançamento de moedas','Duas moedas equilibradas são lançadas ao mesmo tempo. A probabilidade de sair exatamente uma cara é','1/4.','1/2.','3/4.','1.','B','Os resultados equiprováveis são CC, CK, KC e KK; dois dos quatro têm exatamente uma cara.'],
];

const labels = {
  'Linguagens, Códigos e suas Tecnologias': 'Linguagens',
  'Ciências Humanas e suas Tecnologias': 'Ciências Humanas',
  'Ciências da Natureza e suas Tecnologias': 'Ciências da Natureza',
  'Matemática e suas Tecnologias': 'Matemática',
};

const byArea = Object.keys(labels).map((area) => ({ area, short: labels[area], count: questions.filter((q) => q[1] === area).length }));
if (questions.length !== 100 || byArea.some((entry) => entry.count !== 25) || questions.some((q) => q.length !== 11 || !['A','B','C','D'].includes(q[9]))) {
  throw new Error('Validação do banco de questões falhou.');
}

const records = questions.map(([numero, area, habilidade, referencia, enunciado, a, b, c, d, correta, justificativa]) => ({
  numero, area, areaCurta: labels[area], habilidade, referencia, enunciado,
  alternativas: { A: a, B: b, C: c, D: d }, correta, justificativa,
}));

const header = `# SIMULADO ENEM — Caderno de Questões\n\n| Escola | ________________________________________________________________ |\n| --- | --- |\n| Professor(a) | ________________________________________________________________ |\n| Estudante | ________________________________________________________________ |\n| Turma | ____________________ | Data | ____ / ____ / ______ |\n\n> **Material autoral reformulado.** Este caderno foi elaborado a partir de habilidades, temas e estruturas recorrentes em provas oficiais do ENEM. Não reproduz literalmente itens, textos motivadores, imagens ou alternativas dos cadernos do Inep.\n\n## Instruções\n\nLeia cada questão com atenção e assinale **uma única alternativa** na folha de respostas. Este simulado possui 100 questões, quatro alternativas por item e distribuição equilibrada entre as quatro áreas do conhecimento.\n\n## Distribuição\n\n| Área do conhecimento | Questões |\n| --- | ---: |\n${byArea.map((x) => `| ${x.area} | ${x.count} |`).join('\n')}\n| **Total** | **100** |\n\n`;

const formatQuestion = (q) => `### Questão ${String(q.numero).padStart(2,'0')} — ${q.areaCurta}\n\n${q.enunciado}\n\nA. ${q.alternativas.A}\n\nB. ${q.alternativas.B}\n\nC. ${q.alternativas.C}\n\nD. ${q.alternativas.D}\n\n---\n\n`;

const caderno = header + Object.keys(labels).map((area) => `## ${area}\n\n${records.filter((q) => q.area === area).map(formatQuestion).join('')}`).join('\n') + `## Referências de elaboração\n\n[1] [Inep — Provas e Gabaritos do Enem](https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem/provas-e-gabaritos).\n\n[2] [Inep — Matriz de Referência do Enem](https://download.inep.gov.br/download/enem/matriz_referencia.pdf).\n\n[3] [Inep — Cadernos e gabaritos do Enem 2024](https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem/provas-e-gabaritos/2024).\n`;

const gabarito = `# SIMULADO ENEM — Gabarito Comentado\n\n| Escola | ________________________________________________________________ |\n| --- | --- |\n| Professor(a) | ________________________________________________________________ |\n| Turma | ____________________ | Data de correção | ____ / ____ / ______ |\n\n> O gabarito é destinado à correção docente. As justificativas são sintéticas e indicam a operação de leitura, raciocínio ou cálculo esperada.\n\n${Object.keys(labels).map((area) => `## ${area}\n\n| Questão | Gabarito | Habilidade/tema | Justificativa |\n| ---: | :---: | --- | --- |\n${records.filter((q) => q.area === area).map((q) => `| ${q.numero} | **${q.correta}** | ${q.habilidade} — ${q.referencia} | ${q.justificativa} |`).join('\n')}\n`).join('\n')}\n## Referências\n\n[1] [Inep — Provas e Gabaritos do Enem](https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem/provas-e-gabaritos).\n\n[2] [Inep — Matriz de Referência do Enem](https://download.inep.gov.br/download/enem/matriz_referencia.pdf).\n`;

const sheetRows = records.map((q) => `| ${String(q.numero).padStart(3,'0')} | ○ A | ○ B | ○ C | ○ D |`).join('\n');
const maskKey = records.map((q) => `| ${String(q.numero).padStart(3,'0')} | **${q.correta}** |`).join('\n');
const mask = `# SIMULADO ENEM — Folha de Respostas e Máscara de Correção\n\n| Escola | ________________________________________________________________ |\n| --- | --- |\n| Estudante | ________________________________________________________________ |\n| Turma | ____________________ | Data | ____ / ____ / ______ |\n\n> Assinale uma única alternativa por questão. Para correção manual, confira o cartão-resposta com a chave apresentada na segunda parte deste documento.\n\n## Folha de respostas do estudante\n\n| Questão | A | B | C | D |\n| ---: | :---: | :---: | :---: | :---: |\n${sheetRows}\n\n---\n\n# Máscara de correção — uso do(a) professor(a)\n\n> Posicione esta chave ao lado da folha do estudante ou utilize-a para conferência rápida. Cada linha possui uma única resposta correta.\n\n| Questão | Resposta |\n| ---: | :---: |\n${maskKey}\n`;

const ts = `/** Caderno de Campo Pedagógico: dados do simulado ENEM autoral reformulado. */\nexport type Question = {\n  numero: number; area: string; areaCurta: string; habilidade: string; referencia: string;\n  enunciado: string; alternativas: { A: string; B: string; C: string; D: string }; correta: string; justificativa: string;\n};\n\nexport const questions: Question[] = ${JSON.stringify(records, null, 2)};\n\nexport const areaSummary = ${JSON.stringify(byArea, null, 2)};\n`;

const writes = [
  ['caderno_simulado_enem.md', caderno],
  ['gabarito_simulado_enem.md', gabarito],
  ['mascara_correcao.md', mask],
  ['client/src/data/simulado.ts', ts],
  ['simulado_metadata.json', JSON.stringify({ total: records.length, areas: byArea, fontes: ['Inep — Provas e Gabaritos', 'Inep — Matriz de Referência', 'Inep — Cadernos 2024'], aviso: 'Itens autorais reformulados, não reproduções literais de provas oficiais.' }, null, 2)],
];

for (const [relative, content] of writes) {
  const target = resolve(root, relative);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content, 'utf8');
}
console.log(`Materiais gerados: ${records.length} questões; ${byArea.map((x) => `${x.short} ${x.count}`).join(', ')}.`);
