import { ArrowRight, BookOpen, CheckCircle2, FileText, GraduationCap, Printer, Timer } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { filterCatalog, MATH_CATEGORIES, SCHOOL_LEVELS } from "@shared/activityCatalog";

const activities = [
  { title: "Simulado ENEM Interativo", type: "Simulado online", level: "3.ª série", category: "Números e Álgebra", copy: "100 questões, cronômetro, correção por área e relatório de desempenho.", href: "/simulado-enem", status: "Disponível agora" },
  { title: "Trilhas de Álgebra", type: "Lista de exercícios", level: "1.ª série", category: "Números e Álgebra", copy: "Prática gradual de expressões, equações e situações-problema.", href: "/estudante", status: "Em preparação" },
  { title: "Laboratório de Geometria", type: "Atividade guiada", level: "8.º ano", category: "Geometria", copy: "Raciocínio visual e investigação de figuras, ângulos e proporcionalidade.", href: "/estudante", status: "Em preparação" },
  { title: "Medir, comparar e decidir", type: "Lista para impressão", level: "7.º ano", category: "Grandezas e Medidas", copy: "Atividades contextualizadas com medidas, escalas e conversões.", href: "/estudante", status: "Em preparação" },
  { title: "Dados do cotidiano", type: "Desafio online", level: "9.º ano", category: "Probabilidade e Estatística", copy: "Leitura de tabelas, gráficos e situações de chance.", href: "/estudante", status: "Em preparação" },
] as const;

export default function StudentHub() {
  const [level, setLevel] = useState("Todos");
  const [category, setCategory] = useState("Todas");
  const filteredActivities = useMemo(() => filterCatalog(activities, level, category), [level, category]);

  return <div className="hub-page"><header className="hub-header"><Link href="/" className="platform-brand"><span className="platform-brand-mark">M</span><span><strong>ME AJUDA,</strong><em>prof Erasmo!</em></span></Link><div className="hub-header-label"><GraduationCap size={18} /><span>Área do estudante</span></div><Link href="/professor" className="hub-switch">Sou professor(a) <ArrowRight size={14} /></Link></header><main><section className="hub-hero student-hero"><span className="platform-kicker"><i></i> Aprender no seu ritmo</span><h1>Seu próximo passo<br /><em>começa aqui.</em></h1><p>Escolha sua série, encontre o assunto que precisa praticar e avance com atividades online ou prontas para imprimir.</p><div className="hub-benefits"><span><Timer size={16} /> Simulados com tempo</span><span><CheckCircle2 size={16} /> Correção e acompanhamento</span><span><Printer size={16} /> Listas para imprimir</span></div></section><section className="catalog-section"><div className="catalog-heading"><div><span>CATÁLOGO DO ESTUDANTE</span><h2>Praticar também é<br /><em>construir confiança.</em></h2></div><p>{filteredActivities.length} {filteredActivities.length === 1 ? "atividade encontrada" : "atividades encontradas"}</p></div><div className="catalog-filters"><fieldset><legend>Seu ano ou série</legend><div>{SCHOOL_LEVELS.map((item) => <button type="button" className={item === level ? "active" : ""} onClick={() => setLevel(item)} key={item}>{item}</button>)}</div></fieldset><fieldset><legend>O que você quer praticar?</legend><div>{MATH_CATEGORIES.map((item) => <button type="button" className={item === category ? "active" : ""} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div></fieldset></div><div className="activity-grid">{filteredActivities.map((activity) => <article className="activity-card" key={activity.title}><div className="activity-card-top"><span>{activity.type}</span><small className={activity.status === "Disponível agora" ? "ready" : "soon"}>{activity.status}</small></div><h3>{activity.title}</h3><p>{activity.copy}</p><div className="activity-meta"><span>{activity.level}</span><span>{activity.category}</span></div>{activity.status === "Disponível agora" ? <Link href={activity.href}>Começar agora <ArrowRight size={15} /></Link> : <button disabled>Em breve</button>}</article>)}</div></section><section className="hub-callout"><FileText size={28} /><div><span>O SIMULADO JÁ ESTÁ DISPONÍVEL</span><h2>Quer medir sua preparação para o ENEM?</h2><p>Resolva 100 questões autorais, acompanhe os acertos por área e salve seu progresso.</p></div><Link href="/simulado-enem">Abrir simulado <ArrowRight size={16} /></Link></section></main></div>;
}
